# SwiftLint Configuration for SkinLab
# https://github.com/realm/SwiftLint

# Rules to disable
disabled_rules:
  - trailing_whitespace
  - todo # We track TODOs separately
  - opening_brace # Conflicts with SwiftFormat
  - for_where
  - large_tuple
  - legacy_hashing
  - multiple_closures_with_trailing_closure
  - sorted_first_last
  - statement_position
  - trailing_comma
  - unused_optional_binding
  - unused_enumerated
  - vertical_whitespace_closing_braces
  - implicit_optional_initialization

# Opt-in rules
opt_in_rules:
  - empty_count
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - toggle_bool
  - unavailable_function
  - unowned_variable_capture
  - yoda_condition

# Paths to exclude
excluded:
  - Pods
  - DerivedData
  - .build
  - scripts
  - "*.generated.swift"
  - SkinLabTests
  - SkinLabUITests

# Rule configurations
line_length:
  warning: 200
  error: 240
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 1000
  error: 1200
  ignore_comment_only_lines: true

type_body_length:
  warning: 800
  error: 1000

function_body_length:
  warning: 200
  error: 250

cyclomatic_complexity:
  warning: 40
  error: 50

nesting:
  type_level:
    warning: 4
  function_level:
    warning: 5

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - a
    - b
    - f
    - g
    - r
    - n
    - p
    - v
    - id
    - x
    - y
    - i
    - j
    - k

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

function_parameter_count:
  warning: 7
  error: 9

reporter: "xcode"
